### ISSUE TITLE
yaml support

### ISSUE THREAD

**Issue by babafemi99** [babafemi99/testerone#11]
The application should be able to parse in a yaml file and work based on what's in the yaml file

**Comment by Bwise1** [comment]
on this boss. lets say sample yaml file is this right. 
```
endpoints:
  - path: /api/endpoint1
    method: POST
    payload: |
      {"key": "value1"}
  - path: /api/endpoint2
    method: GET
    payload: ""
```
am I correct so I can create a struct to parse it. @babafemi99
